package main.com.java.model;

public class Address {

	
	private String street; 
	private String city; 
	private int zip;
		
	public Address(String street, String city, int zip) {
		super();
		this.street = street;
		this.city = city;
		this.zip = zip;
	}
	public String getAddress() {
		return street;
	}
	public void setAddress(String street) {
		this.street = street;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public int getZip() {
		return zip;
	}
	public void setZip(int zip) {
		this.zip = zip;
	}
	
	//toString generated by eclipse
	@Override
	public String toString() {
		return "Address [address=" + street + ", city=" + city + ", zip=" + zip + "]";
	} 

}
